sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t leomata00/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leomata00/react-test npm test

after_success:
  - docker build -t leomata00/multi-client ./client
  - docker build -t leomata00/multi-nginx ./nginx
  - docker build -t leomata00/multi-server ./server
  - docker build -t leomata00/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push leomata00/multi-client
  - docker push leomata00/multi-nginx
  - docker push leomata00/multi-server
  - docker push leomata00/multi-worker
